language: swift
os: osx
osx_image: xcode9.2
xcode_sdk: iphonesimulator11.2

cache:
  directories:
    - Carthage

before_script:
  - bundle exec danger
  - brew update && brew bundle
  - carthage bootstrap --verbose --no-use-binaries --platform iOS --cache-builds
jobs:
  include:
# ==============================================================================
    - stage: test
      if: NOT (tag IS present)
      env: JOB=iOS Tests
      script:
        - xcodebuild -project CHMeetupApp.xcodeproj -scheme Debug -destination "platform=iOS Simulator,name=iPhone 7 Plus" -enableCodeCoverage YES CODE_SIGNING_REQUIRED=NO CODE_SIGN_IDENTITY="" test | xcpretty -f `xcpretty-travis-formatter`
      after_success:
        - bash <(curl -s https://codecov.io/bash)
# ==============================================================================
